### ISSUE TITLE
Unnecessary else

### ISSUE THREAD

**Issue by zrma** [namonak/DataStructure#1]
https://github.com/namonak/DataStructure/blob/a6b6a6195bad5b543de6446fe0d35f970ef74281/Assignment_1.c#L445

```
if (pTemp == pHead) {
	pNew->next_link = pTemp;
	pHead = pNew;
	break;
}
// Inserted at the middle of the node
else {
	preTemp->next_link = pNew;
	pNew->next_link = pTemp;
	break;
}
```

```
if (pTemp == pHead) {
	pNew->next_link = pTemp;
	pHead = pNew;
	break;
}

preTemp->next_link = pNew;
pNew->next_link = pTemp;
```

차이는?

**Comment by namonak** [comment]
맨아래에 `break;` 문은 생략하신거죠?
조언해 주신대로 코드 수정 후 생각해보니 굳이 `else` 문을 쓸 필요가 없을거 같네요~
어차피 `if` 구문에서 조건문이 `true` 가 아니면 아래로 내려와서 코드 실행하고 `break;` 로 `while` loop 빠져 나갈테니까요.
<pre><code>
if (pTemp == pHead) {

	pNew->next_link = pTemp;
	pHead = pNew;
	break;
}
// Inserted at the middle of the node
preTemp->next_link = pNew;
pNew->next_link = pTemp;
break;
</code></pre>

* 32751f0793ab8c7be6daa135b31c6b3a7219ed6f
