### ISSUE TITLE
one line if body

### ISSUE THREAD

**Issue by zrma** [namonak/DataStructure#2]
https://github.com/namonak/DataStructure/blob/b96348b2845d83fe21e1cb14da2a7f3a4f8c72f3/Assignment_2/Assignment_2.cpp#L23

@namonak 

예전에 애플 소프트웨어에 치명적인 버그가 있었는데

```
if (cond1); 
    expr1
if (cond2)
    expr2
```

`cond1`을 만족하지 않는데도 자꾸 `expr1`도 실행하고 `expr2`도 실행하는 거...

그래서 저 사건 이후로 많은 프로그래밍 언어들이 
* if 구문 뒤 cond 앞뒤 소괄호는 제외하고 (가독성 향상을 위해)
* 따라오는 expression body의 중괄호는 강제하는
방식으로 진화함.

ex)
```
if cond1 {
    expr1
}
if cond2 {
    expr2
}
```

그래서 예전엔 한 줄 몸통은 괄호 없이 그냥 쓰는 코드를 보면 깔끔해 보였지만
내 경우는 지금은 관습적으로 한 줄이라도 무조건 괄호 추가하는데(실수 방지)

어떨까?

**Comment by namonak** [comment]
@zrma 

좋은 사례 알려주셔서 감사합니다! 앞으로 조건문 쓸때는 무조건 중괄호 추가하는 습관을 들여야 겠네요!

a098369041d901d145933b17c2b433311087bd53
